# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-30 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Birth',
            field=models.DateField(null=True, verbose_name='Birth'),
        ),
    ]
