# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-03 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0004_auto_20161230_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='News',
        ),
        migrations.AddField(
            model_name='news',
            name='Tags',
            field=models.ManyToManyField(to='Website.Tags', verbose_name='Tags'),
        ),
    ]
