# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-03 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0005_auto_20170103_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='Content',
            field=models.TextField(max_length=1000, verbose_name='Content'),
        ),
    ]
