# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-03 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0007_comments_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='News',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Website.News', verbose_name='News'),
        ),
    ]
